In [2]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\asus\Downloads\ml project\cleaned_skincare_dataset.csv")

In [5]:
df

,skin_type,climate,humidity_level,cleanser_type,moisturizer_type,sunscreen_type,cleanser_satisfaction,moisturizer_satisfaction,sunscreen_satisfaction,overall_satisfaction
0,Oily,Tropical,High,Foaming Gel Cleanser,Oil-Free Gel Moisturizer,Matte Finish Spf 50,4.5,4.2,4.6,4.4
1,Oily,Tropical,High,Salicylic Acid Cleanser,Water-Based Gel,Lightweight Spf 40,4.7,4.4,4.5,4.5
2,Oily,Tropical,High,Clay Cleanser,Niacinamide Serum-Gel,Spf 50 Fluid,4.3,4.1,4.3,4.2
3,Oily,Tropical,Medium,Foaming Gel Cleanser,Lightweight Lotion,Gel Spf 45,4.4,4.0,4.2,4.2
4,Oily,Tropical,Medium,Salicylic Acid Cleanser,Oil-Free Gel Moisturizer,Invisible Finish Spf 50,4.6,4.3,4.7,4.5
...,...,...,...,...,...,...,...,...,...,...
1076,Combination,Arid/Desert,Low,Pore-Refining Foam Cleanser,Bifida Ferment Lotion,Spf 40 Moisturizing,4.4,4.5,4.2,4.4
1077,Dry,Humid Subtropical,Medium,Lotion Cleanser,Occulsive Barrier Cream,Spf 30 Fluid,4.6,4.7,4.0,4.4
1078,Normal,Arid/Desert,Low,Hydrating Foam Cleanser,Rich Lotion,Mineral Spf 30,4.2,4.6,4.5,4.4
1079,Dry,Temperate,High,Gentle Milk Cleanser,Occulsive Barrier Cream,Water-Resistant Spf 45,4.5,4.9,4.2,4.5
1080,Dry,Cold/Nordic,Low,Lotion Cleanser,Rich Cream Moisturizer,Spf 40 Moisturizing,4.2,4.8,4.4,4.5

In [6]:
print("Dataset Shape:",df.shape)
print("\nFirst 5 row:")
print(df.head())

Dataset Shape: (1081, 10)

First 5 row:
  skin_type   climate humidity_level            cleanser_type  \
0      Oily  Tropical           High     Foaming Gel Cleanser
1      Oily  Tropical           High  Salicylic Acid Cleanser
2      Oily  Tropical           High            Clay Cleanser
3      Oily  Tropical         Medium     Foaming Gel Cleanser
4      Oily  Tropical         Medium  Salicylic Acid Cleanser

           moisturizer_type           sunscreen_type  cleanser_satisfaction  \
0  Oil-Free Gel Moisturizer      Matte Finish Spf 50                    4.5
1           Water-Based Gel       Lightweight Spf 40                    4.7
2     Niacinamide Serum-Gel             Spf 50 Fluid                    4.3
3        Lightweight Lotion               Gel Spf 45                    4.4
4  Oil-Free Gel Moisturizer  Invisible Finish Spf 50                    4.6

   moisturizer_satisfaction  sunscreen_satisfaction  overall_satisfaction
0                       4.2                     4.6                   4.4
1                       4.4                     4.5                   4.5
2                       4.1                     4.3                   4.2
3                       4.0                     4.2                   4.2
4                       4.3                     4.7                   4.5

In [7]:
print("\nMissing Values:")   #missing value
print(df.isnull().sum())

Missing Values:
skin_type                   0
climate                     0
humidity_level              0
cleanser_type               0
moisturizer_type            0
sunscreen_type              0
cleanser_satisfaction       0
moisturizer_satisfaction    0
sunscreen_satisfaction      0
overall_satisfaction        0
dtype: int64

In [8]:
df=df.drop_duplicates() #duplicates
df

,skin_type,climate,humidity_level,cleanser_type,moisturizer_type,sunscreen_type,cleanser_satisfaction,moisturizer_satisfaction,sunscreen_satisfaction,overall_satisfaction
0,Oily,Tropical,High,Foaming Gel Cleanser,Oil-Free Gel Moisturizer,Matte Finish Spf 50,4.5,4.2,4.6,4.4
1,Oily,Tropical,High,Salicylic Acid Cleanser,Water-Based Gel,Lightweight Spf 40,4.7,4.4,4.5,4.5
2,Oily,Tropical,High,Clay Cleanser,Niacinamide Serum-Gel,Spf 50 Fluid,4.3,4.1,4.3,4.2
3,Oily,Tropical,Medium,Foaming Gel Cleanser,Lightweight Lotion,Gel Spf 45,4.4,4.0,4.2,4.2
4,Oily,Tropical,Medium,Salicylic Acid Cleanser,Oil-Free Gel Moisturizer,Invisible Finish Spf 50,4.6,4.3,4.7,4.5
...,...,...,...,...,...,...,...,...,...,...
1076,Combination,Arid/Desert,Low,Pore-Refining Foam Cleanser,Bifida Ferment Lotion,Spf 40 Moisturizing,4.4,4.5,4.2,4.4
1077,Dry,Humid Subtropical,Medium,Lotion Cleanser,Occulsive Barrier Cream,Spf 30 Fluid,4.6,4.7,4.0,4.4
1078,Normal,Arid/Desert,Low,Hydrating Foam Cleanser,Rich Lotion,Mineral Spf 30,4.2,4.6,4.5,4.4
1079,Dry,Temperate,High,Gentle Milk Cleanser,Occulsive Barrier Cream,Water-Resistant Spf 45,4.5,4.9,4.2,4.5
1080,Dry,Cold/Nordic,Low,Lotion Cleanser,Rich Cream Moisturizer,Spf 40 Moisturizing,4.2,4.8,4.4,4.5

In [18]:
df=df.dropna()
df

,skin_type,climate,humidity_level,cleanser_type,moisturizer_type,sunscreen_type,cleanser_satisfaction,moisturizer_satisfaction,sunscreen_satisfaction,overall_satisfaction
0,Oily,Tropical,High,Foaming Gel Cleanser,Oil-Free Gel Moisturizer,Matte Finish SPF 50,4.5,4.2,4.6,4.4
1,Oily,Tropical,High,Salicylic Acid Cleanser,Water-Based Gel,Lightweight SPF 40,4.7,4.4,4.5,4.5
2,Oily,Tropical,High,Clay Cleanser,Niacinamide Serum-Gel,SPF 50 Fluid,4.3,4.1,4.3,4.2
3,Oily,Tropical,Medium,Foaming Gel Cleanser,Lightweight Lotion,Gel SPF 45,4.4,4.0,4.2,4.2
4,Oily,Tropical,Medium,Salicylic Acid Cleanser,Oil-Free Gel Moisturizer,Invisible Finish SPF 50,4.6,4.3,4.7,4.5
...,...,...,...,...,...,...,...,...,...,...
1076,Combination,Arid/Desert,Low,Pore-Refining Foam Cleanser,Bifida Ferment Lotion,SPF 40 Moisturizing,4.4,4.5,4.2,4.4
1077,Dry,Humid Subtropical,Medium,Lotion Cleanser,Occulsive Barrier Cream,SPF 30 Fluid,4.6,4.7,4.0,4.4
1078,Normal,Arid/Desert,Low,Hydrating Foam Cleanser,Rich Lotion,Mineral SPF 30,4.2,4.6,4.5,4.4
1079,Dry,Temperate,High,Gentle Milk Cleanser,Occulsive Barrier Cream,Water-Resistant SPF 45,4.5,4.9,4.2,4.5
1080,Dry,Cold/Nordic,Low,Lotion Cleanser,Rich Cream Moisturizer,SPF 40 Moisturizing,4.2,4.8,4.4,4.5

In [9]:
text_columns = df.select_dtypes(include='object').columns  #standardize text column
for col in text_columns:
    df[col] = df[col].str.strip() 
    df[col] = df[col].str.title()

In [10]:
text_columns

Index(['skin_type', 'climate', 'humidity_level', 'cleanser_type',
       'moisturizer_type', 'sunscreen_type'],
      dtype='object')

In [11]:
#check uniqe values in categarical column
for col in text_columns:
    print(f"\nUnique values in {col}:")
    print(df[col].unique())

Unique values in skin_type:
['Oily' 'Dry' 'Combination' 'Sensitive' 'Normal' 'Acne-Prone']

Unique values in climate:
['Tropical' 'Arid/Desert' 'Temperate' 'Cold/Nordic' 'Humid Subtropical']

Unique values in humidity_level:
['High' 'Medium' 'Low']

Unique values in cleanser_type:
['Foaming Gel Cleanser' 'Salicylic Acid Cleanser' 'Clay Cleanser'
 'Gentle Foaming Cleanser' 'Micellar Cleanser' 'Gel Cleanser'
 'Foaming Cleanser' 'Gentle Gel Cleanser' 'Cream-To-Foam Cleanser'
 'Salicylic Acid Gel Cleanser' 'Cream Cleanser' 'Milk Cleanser'
 'Hydrating Gel Cleanser' 'Oil Cleanser' 'Balm Cleanser' 'Lotion Cleanser'
 'Hydrating Foam Cleanser' 'Balancing Foam Cleanser' 'Salicylic Acid Gel'
 'Mild Foam Cleanser' 'Balancing Cleanser' 'Foam Cleanser'
 'Mild Gel Cleanser' 'Cream-Gel Cleanser' 'Balancing Gel Cleanser'
 'Fragrance-Free Cream Cleanser' 'Micellar Gentle Cleanser'
 'Gentle Milk Cleanser' 'Ultra-Gentle Cream Cleanser'
 'Oil Cleanser Fragrance-Free' 'Gentle Foam Cleanser'
 'Gentle Cream Cleanser' 'Fragrance-Free Foam Cleanser' 'Mild Cleanser'
 'Benzoyl Peroxide Cleanser' 'Bha Gel Cleanser'
 'Gentle Salicylic Acid Cleanser' 'Clay Gel Cleanser' 'Bha Foam Cleanser'
 'Gentle Bha Cleanser' 'Mild Acne Cleanser' 'Bha + Tea Tree Cleanser'
 'Salicylic + Niacinamide Cleanser' 'Refreshing Gel Cleanser'
 'Oil-Control Foam Cleanser' 'Soothing Gel Cleanser' 'Charcoal Cleanser'
 'Nourishing Cream Cleanser' 'Niacinamide Cleanser' 'Oat Extract Cleanser'
 'Daily Foam Cleanser' 'Micellar Balancing Cleanser'
 'Gentle Balancing Cleanser' 'Zinc Cleanser' 'Aloe Vera Cleanser'
 'Tea Tree Gel Cleanser' 'Chamomile Cream Cleanser' 'Aha+Bha Cleanser'
 'Tea Tree Bha Cleanser' 'Calamine Gentle Cleanser'
 'Retinol Gentle Cleanser' 'Green Tea Foam Cleanser'
 'Centella Asiatica Cleanser' 'Vitamin C Foam Cleanser' 'Sulfur Cleanser'
 'Honey Balm Cleanser' 'Witch Hazel Gel Cleanser' 'Kaolin Clay Cleanser'
 'Avocado Cream Cleanser' 'Brightening Gel Cleanser'
 'Pore-Refining Foam Cleanser']

Unique values in moisturizer_type:
['Oil-Free Gel Moisturizer' 'Water-Based Gel' 'Niacinamide Serum-Gel'
 'Lightweight Lotion' 'Light Gel Moisturizer' 'Hydrating Oil-Free Lotion'
 'Water-Gel Moisturizer' 'Gel Moisturizer' 'Lightweight Serum Moisturizer'
 'Balancing Moisturizer' 'Hydrating Gel Lotion'
 'Light Moisture Barrier Cream' 'Oil-Control Gel'
 'Niacinamide Gel Moisturizer' 'Rich Cream Moisturizer'
 'Shea Butter Cream' 'Ceramide Cream' 'Heavy Emollient Cream'
 'Shea + Hyaluronic Acid Cream' 'Occulsive Barrier Cream' 'Rich Lotion'
 'Ceramide Lotion' 'Hyaluronic Acid Cream' 'Rich Emollient Cream'
 'Ultra-Rich Barrier Cream' 'Thick Moisturizing Cream'
 'Ceramide + Peptide Cream' 'Light Hydrating Gel-Cream'
 'Moisture Surge Cream' 'Balancing Gel-Cream' 'Zone-Control Moisturizer'
 'Lightweight Balancing Lotion' 'Hydrating Balancing Cream'
 'Gel-Cream Moisturizer' 'Lightweight Dual-Action Lotion'
 'Hydrating Gel-Cream' 'Balancing Cream' 'Ceramide Balancing Lotion'
 'Oil-Free Gel With Hyaluronic Acid' 'Lightweight Balancing Serum'
 'Gentle Aloe Gel Moisturizer' 'Soothing Lotion' 'Soothing Cream'
 'Rich Sensitive Cream' 'Barrier Repair Cream' 'Ceramide Soothing Lotion'
 'Sensitive Skin Lotion' 'Soothing Hydrating Cream'
 'Barrier Repair Moisturizer' 'Ultra-Rich Sensitive Cream'
 'Soothing Occulsive Cream' 'Ceramide + Niacinamide Cream'
 'Lightweight Soothing Gel' 'Aloe + Ceramide Lotion' 'Hydrating Lotion'
 'Light Cream Moisturizer' 'Balanced Lotion' 'Daily Moisturizer Spf'
 'Hydrating Cream' 'Daily Lotion' 'Moisturizing Cream'
 'Lightweight Gel-Lotion' 'Balancing Lotion' 'Oil-Free Niacinamide Gel'
 'Lightweight Anti-Acne Gel' 'Salicylic Acid Moisturizer'
 'Hydrating Anti-Acne Lotion' 'Non-Comedogenic Cream'
 'Non-Comedogenic Lotion' 'Lightweight Gel Moisturizer'
 'Hydrating Non-Comedogenic Cream' 'Pore-Minimizing Gel'
 'Daily Moisturizer' 'Gel-Lotion' 'Hyaluronic Acid Gel'
 'Adaptive Moisture Gel' 'Bifida Ferment Lotion' 'Centella Calming Cream'
 'Azelaic Acid Lotion' 'Peptide Moisturizer'
 'Mattifying Fluid Moisturizer' 'Lanolin-Free Rich Cream' 'Squalane Cream'
 'Madecassoside Cream']

Unique values in sunscreen_type:
['Matte Finish Spf 50' 'Lightweight Spf 40' 'Spf 50 Fluid' 'Gel Spf 45'
 'Invisible Finish Spf 50' 'Dry-Touch Spf 50' 'Spf 30 Fluid'
 'Matte Spf 40' 'Spf 30 Gel' 'Spf 50 Invisible' 'Broad Spectrum Spf 30'
 'Spf 30 Moisturizing' 'Spf 30 Tinted' 'Waterproof Spf 50'
 'Lightweight Spf 50' 'Hydrating Spf 30' 'Spf 40 Moisturizing'
 'Spf 30 Cream' 'Spf 50 Hydrating Cream' 'Spf 40 Nourishing'
 'Spf 30 Mineral Tinted' 'Spf 40 Lightweight' 'Spf 50 Cream'
 'Spf 30 Barrier' 'Spf 30 Enriched' 'Spf 30 Hydrating' 'Spf 40 Serum'
 'Spf 40 Dry-Touch' 'Spf 30 Invisible' 'Spf 30 Broad Spectrum'
 'Spf 40 Fluid' 'Mineral Spf 30' 'Zinc Oxide Spf 50'
 'Physical Spf 30 Tinted' '100% Mineral Spf 40' 'Spf 30 Mineral Lotion'
 'Fragrance-Free Spf 30' 'Mineral Broad Spectrum Spf 30'
 'Spf 40 Sensitive Skin' 'Spf 30 Mineral Enriched' 'Mineral Spf 30 Tinted'
 'Gentle Spf 30 Mineral' 'Mineral Spf 50 Lightweight' 'Physical Spf 40'
 'Spf 50 Lightweight' 'Spf 30 2-In-1' 'Matte Spf 50' 'Spf 40 Mattifying'
 'Oil-Free Spf 30' 'Spf 30 Oil-Free' 'Spf 40 Invisible' 'Spf 30 Gentle'
 'Waterproof Matte Spf 50' 'Spf 50 Oil-Free' 'Water-Resistant Spf 45'
 'Spf 50 Gel' 'Hydrating Spf 50' 'Spf 30 Mattifying' 'Invisible Spf 40'
 'Sweat-Proof Spf 50' 'Oil-Control Spf 50 Pa++++' 'Tinted Spf 40'
 'Spf 50 Nourishing Lotion' 'Spf 30 Serum Sunscreen']

In [12]:
# Check data types
print("\nData Types:")
print(df.dtypes)

Data Types:
skin_type                    object
climate                      object
humidity_level               object
cleanser_type                object
moisturizer_type             object
sunscreen_type               object
cleanser_satisfaction       float64
moisturizer_satisfaction    float64
sunscreen_satisfaction      float64
overall_satisfaction        float64
dtype: object

In [13]:
df.to_csv("cleaned_skincare_dataset.csv", index=False)

print("\nData cleaning completed successfully!")
print("Cleaned dataset saved as 'cleaned_skincare_dataset.csv'")

Data cleaning completed successfully!
Cleaned dataset saved as 'cleaned_skincare_dataset.csv'

In [14]:
import pandas as pd



df=pd.read_csv("cleaned_skincare_dataset.csv")
print(df.head())
print("\nDataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nSummary Statistics:")
print(df.describe(include='all'))

  skin_type   climate humidity_level            cleanser_type  \
0      Oily  Tropical           High     Foaming Gel Cleanser
1      Oily  Tropical           High  Salicylic Acid Cleanser
2      Oily  Tropical           High            Clay Cleanser
3      Oily  Tropical         Medium     Foaming Gel Cleanser
4      Oily  Tropical         Medium  Salicylic Acid Cleanser

           moisturizer_type           sunscreen_type  cleanser_satisfaction  \
0  Oil-Free Gel Moisturizer      Matte Finish Spf 50                    4.5
1           Water-Based Gel       Lightweight Spf 40                    4.7
2     Niacinamide Serum-Gel             Spf 50 Fluid                    4.3
3        Lightweight Lotion               Gel Spf 45                    4.4
4  Oil-Free Gel Moisturizer  Invisible Finish Spf 50                    4.6

   moisturizer_satisfaction  sunscreen_satisfaction  overall_satisfaction
0                       4.2                     4.6                   4.4
1                       4.4                     4.5                   4.5
2                       4.1                     4.3                   4.2
3                       4.0                     4.2                   4.2
4                       4.3                     4.7                   4.5

Dataset Shape: (1081, 10)

Column Names:
Index(['skin_type', 'climate', 'humidity_level', 'cleanser_type',
       'moisturizer_type', 'sunscreen_type', 'cleanser_satisfaction',
       'moisturizer_satisfaction', 'sunscreen_satisfaction',
       'overall_satisfaction'],
      dtype='object')

Summary Statistics:
       skin_type            climate humidity_level cleanser_type  \
count       1081               1081           1081          1081
unique         6                  5              3            71
top          Dry  Humid Subtropical            Low  Gel Cleanser
freq         193                227            377            50
mean         NaN                NaN            NaN           NaN
std          NaN                NaN            NaN           NaN
min          NaN                NaN            NaN           NaN
25%          NaN                NaN            NaN           NaN
50%          NaN                NaN            NaN           NaN
75%          NaN                NaN            NaN           NaN
max          NaN                NaN            NaN           NaN

             moisturizer_type    sunscreen_type  cleanser_satisfaction  \
count                    1081              1081             1081.00000
unique                     84                64                    NaN
top     Water-Gel Moisturizer  Invisible Spf 40                    NaN
freq                       49                48                    NaN
mean                      NaN               NaN                4.43321
std                       NaN               NaN                0.26520
min                       NaN               NaN                3.30000
25%                       NaN               NaN                4.30000
50%                       NaN               NaN                4.40000
75%                       NaN               NaN                4.60000
max                       NaN               NaN                5.00000

        moisturizer_satisfaction  sunscreen_satisfaction  overall_satisfaction
count                1081.000000             1081.000000           1081.000000
unique                       NaN                     NaN                   NaN
top                          NaN                     NaN                   NaN
freq                         NaN                     NaN                   NaN
mean                    4.458464                4.341166              4.410268
std                     0.298616                0.289281              0.164418
min                     3.400000                3.400000              3.800000
25%                     4.300000                4.200000              4.300000
50%                     4.500000                4.300000              4.400000
75%                     4.700000                4.500000              4.500000
max                     5.000000                5.000000              4.900000

In [37]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import joblib

# Load cleaned dataset
df = pd.read_csv("cleaned_skincare_dataset.csv")

# Dictionary to store encoders
encoders = {}

# Encode all categorical columns
for column in df.columns:
    if df[column].dtype == "object":
        le = LabelEncoder()
        df[column] = le.fit_transform(df[column])
        encoders[column] = le

# Save encoded dataset
df.to_csv("encoded_skincare_dataset.csv", index=False)

# Save encoders
joblib.dump(encoders, "label_encoders.pkl")

print("Encoding completed successfully!")

Encoding completed successfully!

In [38]:
import pandas as pd

df = pd.read_csv("encoded_skincare_dataset.csv")

# Features
X = df.drop("overall_satisfaction", axis=1)

# Target
y = df["overall_satisfaction"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1081, 9)
Target shape: (1081,)

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 864
Testing samples: 217

In [40]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load encoded dataset
df = pd.read_csv("encoded_skincare_dataset.csv")

# Features and Target
X = df.drop("overall_satisfaction", axis=1)
y = df["overall_satisfaction"]

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create and train the model
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print("R² Score:", r2_score(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

R² Score: 0.9314878597027513
Mean Absolute Error: 0.031442396313364075
Mean Squared Error: 0.001656373271889397

In [41]:
X = df[["skin_type", "climate", "humidity_level"]]

y = df[[
    "cleanser_type",
    "moisturizer_type",
    "sunscreen_type"
]]

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [43]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier

model = MultiOutputClassifier(
    RandomForestClassifier(
        n_estimators=100,
        random_state=42
    )
)

model.fit(X_train, y_train)

MultiOutputClassifier(estimator=RandomForestClassifier(random_state=42))

In [44]:
pred = model.predict(X_test)

print(pred[:5])

[[67 17 16]
 [51 65 12]
 [51 65 12]
 [16 60 33]
 [38 23 16]]

In [45]:
from sklearn.metrics import accuracy_score

for i, column in enumerate(y.columns):
    acc = accuracy_score(y_test.iloc[:, i], pred[:, i])
    print(f"{column} Accuracy: {acc:.2f}")

cleanser_type Accuracy: 0.08
moisturizer_type Accuracy: 0.09
sunscreen_type Accuracy: 0.08

In [46]:
new_user = pd.DataFrame({
    "skin_type": ["Oily"],
    "climate": ["Tropical"],
    "humidity_level": ["High"]
})

# Encode the inputs
for col in new_user.columns:
    new_user[col] = encoders[col].transform(new_user[col])

# Predict
prediction = model.predict(new_user)

# Decode the predictions
cleanser = encoders["cleanser_type"].inverse_transform([prediction[0][0]])[0]
moisturizer = encoders["moisturizer_type"].inverse_transform([prediction[0][1]])[0]
sunscreen = encoders["sunscreen_type"].inverse_transform([prediction[0][2]])[0]

print("Recommended Cleanser:", cleanser)
print("Recommended Moisturizer:", moisturizer)
print("Recommended Sunscreen:", sunscreen)

#this is test with new user

Recommended Cleanser: Salicylic Acid Cleanser
Recommended Moisturizer: Hydrating Oil-Free Lotion
Recommended Sunscreen: Lightweight Spf 50

In [48]:
import joblib

joblib.dump(model, "skincare_model.pkl")
print("Model saved!")

Model saved!

In [49]:
import joblib

joblib.dump(model, "skincare_model.pkl")
joblib.dump(encoders, "label_encoders.pkl")

print("Model saved successfully!")

Model saved successfully!

In [50]:
import os

print(os.listdir())

['.ipynb_checkpoints', 'app.py', 'cleaned_dataset.csv', 'cleaned_skincare_dataset.csv', 'encoded_skincare_dataset.csv', 'label_encoders.pkl', 'ml-Copy1.ipynb', 'ml.ipynb', 'skincare_model.pkl', 'skin_banner.jpg', 'Untitled.ipynb', 'untitled.txt', 'untitled1.txt', 'Untitled10-Copy1.ipynb', 'Untitled10.ipynb']

In [51]:
import os

size = os.path.getsize("skincare_model.pkl") / (1024 * 1024)
print(f"Model size: {size:.2f} MB")

Model size: 30.40 MB

In [52]:
joblib.dump(model, "skincare_model.pkl", compress=9)

['skincare_model.pkl']

In [53]:
import os

size = os.path.getsize("skincare_model.pkl") / (1024 * 1024)
print(f"Model size: {size:.2f} MB")

Model size: 2.41 MB

In [17]:
#install streamelit

In [18]:
pip install streamlit

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in c:\programdata\anaconda3\lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\programdata\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\programdata\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

['label_encoders.pkl']

In [22]:
#creatin the appp

In [1]:
# import pickle

# with open("skincare_model.pkl", "wb") as f:
#     pickle.dump(model, f)

NameError: name 'model' is not defined

In [26]:
streamlit run app.py

SyntaxError: invalid syntax (3737097518.py, line 1)